User.create(first_name: "Asim", last_name: "Kaghzi", username: "akaghzi", user_type: "doctor", password: "hussain7", password_confirmation: "hussain7")
User.create(first_name: "Jamila", last_name: "Kureshi", username: "jkureshi", user_type: "doctor", password: "jamilah", password_confirmation: "jamilah")
Patient.create(first_name: "John", middle_name: "Smith", last_name: "Doe", gender: "male", date_of_birth: "1968-01-01", phone: "4035552345", externalid: "123211")
Patient.create(first_name: "Mary", middle_name: "Smith", last_name: "Jane", gender: "female", date_of_birth: "1998-12-11", phone: "3035552345", externalid: "123213")
Patient.create(first_name: "Little", middle_name: "Smith", last_name: "Jonny", gender: "male", date_of_birth: "2007-11-21", phone: "2035552345", externalid: "1332221")
RegQuestion.create(content: 'existing medical problems [put none, if none]',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'past medical problems [excluding surgeries]',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'for children < 18 years, problems or complications of pregnancy, labor, delivery, or early newborn period, adults skip this ',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'other healthcare provider, if so, include names and for what condition they are involved',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'indicate history of medical problems of your family and your relationship, like heart disease, cancer, brother , mother etc',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recent tests done, i.e., cholestrol, blood work, urine analysis, x-ray, please bring in test reports for accuracy',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'reproductive history, i.e., pregnancy, still births, births , mamograms, menopause, bone density test',minimum_age: 18,gender: 'female')
RegQuestion.create(content: 'men\'s screening, i.e., prostrate cancer etc',minimum_age: 40,gender: 'male')
RegQuestion.create(content: 'occupation, include number of hours per week work',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'recreational activities you enjoy',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'smoking or pan / gutka chewing , if so then frequenct of use, if quite then what year',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'alchohol drinking, if so, what frequency?',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'substance abuse, if so, what type of substance, quantities and frequency, if quit then what year',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'recent changes to weight, chills, fever, excessive fatigue',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recent changes to sense of smell, ability to chew or swallow, vision, hearing',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'any recent occurance of shortness of breath, wheezing, heart racing, difficulty breathing while sleeping or leg swelling etc',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of digestion, nasuea, vomiting, abdominal pain, diarrhea, constipation, blood in stool, changes in bowel movement, color or frequency etc',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of back pain, joint pain, injuries',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of dizziness, headache, unusual numbness or tingling sensation, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'during the past month have you felt depressed, down, or hopeless, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'any concerned related to sexual functions, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'recent changes in urination, frequency, color , pain, burning sensation, difficulty starting or stopping stream of urine, blood in urine, leakage etc',minimum_age: 10,gender: 'both')
RegQuestion.create(content: 'any other problem or concern',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'how did you hear about us',minimum_age: 18,gender: 'both')
LabTest.create(full_name: "Blood Culture", short_name: "BLCS", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Abo blood group & rh fact", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Abo incomp titre", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Absolute eosino", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Acid fast bacilli smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Acute lukemia basic panel", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Adrenocorticotropic hormo", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Afb culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Afb culture and sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Afb culture without susceptibility testing", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Alcohol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Aldosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Alk. Phos. Fractionation.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Alkaline phosphatase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Amoebaiasis - iha", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ana group test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Androstenedione", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Angiotensin conver. Enzy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti dsdna", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti thrombin iii", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti transglutaminase-iga", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti xa assay", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti-cardiolipin igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti-thyroglobuline ( anti-tg )", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Anti-thyroid peroxidase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Antibodies to heparin/platelet factor 4 comple", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Antistreptolysin 'o'", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Aptt", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Aptt inhibitor test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ascitic fluid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ascitic fluid-albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "B.pertussis dna by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "B12", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Bence jones protein(qual)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Bilirubin group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Bladder cancer urovysion", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Bleeding time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Blood culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Blood culture bottle", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Blood indices", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Blood urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Blood1 x-match/screen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Body fluid amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Body fluid ldh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Body fluid ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Body fluid-albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Breath h2 test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Calcium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Cardiac enz.profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Cbc esr platelets", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ceruloplasmin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Cervical smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Chlamydia trachomatis ag.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Cholesterol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ckmb", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Clostridium difficile gdh antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Clostridium difficile toxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Clotting time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Complete blood count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Cpk", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Creatinine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Creatinine clearance", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Creatinine urine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Crossmatch", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Crossmatch only", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Cryoprecipitate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Csf glucose", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Csf igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Csf protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Csf protein electrop", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Culture & sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Culture and sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Dengue igm antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Dengue rapid ns1 antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Diff.leucocytes count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Digoxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Direct bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Direct coombs(broad spect", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Environmental allergens", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Environmental culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Enzyme histo chemistry", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Esr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Estradiol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ferritin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Fibrin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Fine ndl asp cyto & proc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Fine needle asp cytology", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Fine needle aspiratn bio", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Folic acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Follicle stimulating horm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "For gynae ogtt-gd 2hr-75gm.f,1h,2hs", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Free haemoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Free prostate specific ag", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Free thyroxine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Free thyroxine index", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Free triiodothyronine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Fungus culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Fungus smear/koh prep", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "G6pd quantitative", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Glucose challenge test.1 fl tube", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Glucose fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Glucose random", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Glycated hemoglobin (a1c)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Gram stain", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Gtt 3hr-75gm.8--12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Gtt-4hr 09 fl tubes required.8-12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Gtt-5 hrs 11 fl tubes required.8-12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "H-urine bile pigment", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "H-urine bile salts", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "H.pylori antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Haemoglobin haematocrit", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Haptoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hb electroph. On acid ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hb electrophoresis report", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hb h inclusion", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hbv genotyping", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hcv rna genotyping", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hemosiderin urine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep b.surface antigen quantitative", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.a antibody igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.b core igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.b core total", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.b sur. Antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.b.sur.antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.be antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.be antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hep.delta antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatitis a virus ab tot.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatitis b virus by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatitis e virus (hev) by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatitis e virus (igg)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatitis e virus igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatitis profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatits b profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hepatits c virus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "High density lipoprotein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "High sensitive crp", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Hiv by western blot", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Infectious mono", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Influenza a h1n1 pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Influenza a h1n1 pcr minus swab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Insulin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Insulin sensitivity test with ogtt", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Ldh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Legionella urine antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Lipase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Lipid profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Lipoprot.electrophoresis", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Liver kidney microsoml ab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Liver profile (lft)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Low density lipoprotein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Magnesium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Malaria parasites", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Mantoux test (ppd)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Mycoplasma pneumoniae ab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Neonatal bilirubin group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Neonatal total bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Neonatal tsh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Nt-pro bnp ii", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Pap smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Pap smear procedure chg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Parathormone *", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Paroxysmal nocturnal haem", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Phenobarbital", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Phenytoin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Phosphorus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Plasma zinc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Platelet aggregation", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Platelets", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Prostate specific antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Protein electrophoresi", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Prothrombin time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Q.r.a test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Qualitative hcv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Qualitative hiv by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quality control culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantification of post transplant donor chimerism", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantification of pre transplant donor chimerism", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantitative culture & se", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantitative hbv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantitative hcv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantitative hdv by real time pcr (qhdv)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Quantitative hiv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Rbc folate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Reticulocytes", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Rota virus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Rubella igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Rubella igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "S.bicarbonate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "S.chloride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "S.methotrexate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "S.potassium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "S.sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sec blood x-match/screen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum anca", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum electrolytes", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum ena profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum immunoglobulins", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum iron", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum iron/tibc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Serum protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sgot (ast)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sgpt(alt)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Short synachten-17oh prog", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Short synachten-cortisol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Skin biopsy procedure", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Skin biopsy procedure chg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Skin window", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Slide consultation review", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sma 6 (gluf,bun,cr,electrolyte", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sperm antibody(auto)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sperm antibody(wife's)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spinal muscular atrophy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine ca", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine chloride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine creatinine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine phosphorous", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine potasium (non-stat entity)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Spot urine zinc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Sputum for eosinophils", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Stool d/r concentration m", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Stool detail report", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Stool fat globules", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Stool occult blood", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Synovial fluid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Tegretol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Testosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thalassemia by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thalassemia pcr in blood", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thrombin time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thyroglobulin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thyroid profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thyroid stimulating hormo", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Thyroxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Torch", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Total bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Total hla typing", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Total iron bind.capacity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Total protein group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Total urine volume", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Triglyceride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Triidothyronine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "U.barbiturates", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "U.benzodiazepines", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urinary beta-2 microglubu", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urinary beta-2-microglobu", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urinary copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urinary metabolites", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urinary myoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urinary toxicology", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine aldosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine calcium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine microalbumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine microscopy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine osmolality", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine reducing substance", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Urine uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Valproic acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Vancomycin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Vdrl / rpr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "White blood cell count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "Widal", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "X culture & sensi", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
