Relationship.create(name: "self")
Relationship.create(name: "mother")
Relationship.create(name: "father")
Relationship.create(name: "sister")
Relationship.create(name: "brother")
Relationship.create(name: "mother's mom")
Relationship.create(name: "mother's father")
Relationship.create(name: "father's mom")
Relationship.create(name: "father's father")