Disease.create(name: "arthritis")
Disease.create(name: "asthma")
Disease.create(name: "blood disorder")
Disease.create(name: "cancer")
Disease.create(name: "diabetes")
Disease.create(name: "gastrointestinal")
Disease.create(name: "genitourinary")
Disease.create(name: "heart problems")
Disease.create(name: "high blood pressure")
Disease.create(name: "high cholesterol")
Disease.create(name: "kidney problems")
Disease.create(name: "liver problems/hepatitis")
Disease.create(name: "lung problems")
Disease.create(name: "neuro-epilepsy")
Disease.create(name: "neuro-seizures")
Disease.create(name: "other")
Disease.create(name: "prostate")
Disease.create(name: "psychiatric")
Disease.create(name: "skin disorders")
Disease.create(name: "std")
Disease.create(name: "thyroid")
LabTest.create(full_name: "abo blood group & rh fact", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "abo incomp titre", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "absolute eosino", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "acid fast bacilli smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "acute lukemia basic panel", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "adrenocorticotropic hormo", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "afb culture and sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "afb culture without susceptibility testing", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "afb culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "alcohol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "aldosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "alk. phos. fractionation.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "alkaline phosphatase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "amoebaiasis - iha", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ana group test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "androstenedione", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "angiotensin conver. enzy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti dsdna", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti thrombin iii", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti transglutaminase-iga", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti xa assay", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti-cardiolipin igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti-thyroglobuline ( anti-tg )", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti-thyroid peroxidase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "antibodies to heparin/platelet factor 4 comple", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "antistreptolysin 'o'", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "aptt inhibitor test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "aptt", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ascitic fluid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ascitic fluid-albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "b.pertussis dna by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "b12", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bence jones protein(qual)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bilirubin group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bladder cancer urovysion", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bleeding time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood culture bottle", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood culture", short_name: "blcs", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood indices", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood1 x-match/screen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid ldh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid-albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "breath h2 test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "calcium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cardiac enz.profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cbc esr platelets", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ceruloplasmin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cervical smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "chlamydia trachomatis ag.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cholesterol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ckmb", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "clostridium difficile gdh antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "clostridium difficile toxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "clotting time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "complete blood count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cpk", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "creatinine clearance", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "creatinine urine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "creatinine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "crossmatch only", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "crossmatch", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cryoprecipitate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf glucose", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf protein electrop", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "culture & sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "culture and sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "dengue igm antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "dengue rapid ns1 antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "diff.leucocytes count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "digoxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "direct bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "direct coombs(broad spect", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "environmental allergens", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "environmental culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "enzyme histo chemistry", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "esr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "estradiol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ferritin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fibrin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fine ndl asp cyto & proc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fine needle asp cytology", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fine needle aspiratn bio", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "folic acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "follicle stimulating horm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "for gynae ogtt-gd 2hr-75gm.f,1h,2hs", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free haemoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free prostate specific ag", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free thyroxine index", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free thyroxine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free triiodothyronine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fungus culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fungus smear/koh prep", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "g6pd quantitative", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glucose challenge test.1 fl tube", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glucose fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glucose random", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glycated hemoglobin (a1c)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gram stain", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gtt 3hr-75gm.8--12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gtt-4hr 09 fl tubes required.8-12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gtt-5 hrs 11 fl tubes required.8-12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "h-urine bile pigment", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "h-urine bile salts", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "h.pylori antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "haemoglobin haematocrit", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "haptoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hb electroph. on acid ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hb electrophoresis report", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hb h inclusion", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hbv genotyping", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hcv rna genotyping", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hemosiderin urine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep b.surface antigen quantitative", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.a antibody igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b core igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b core total", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b sur. antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b.sur.antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.be antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.be antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.delta antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis a virus ab tot.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis b virus by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis e virus (hev) by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis e virus (igg)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis e virus igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatits b profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatits c virus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "high density lipoprotein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "high sensitive crp", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hiv by western blot", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "infectious mono", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "influenza a h1n1 pcr minus swab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "influenza a h1n1 pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "insulin sensitivity test with ogtt", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "insulin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ldh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "legionella urine antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "lipase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "lipid profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "lipoprot.electrophoresis", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "liver kidney microsoml ab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "liver profile (lft)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "low density lipoprotein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "magnesium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "malaria parasites", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "mantoux test (ppd)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "mycoplasma pneumoniae ab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "neonatal bilirubin group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "neonatal total bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "neonatal tsh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "nt-pro bnp ii", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "pap smear procedure chg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "pap smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "parathormone *", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "paroxysmal nocturnal haem", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "phenobarbital", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "phenytoin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "phosphorus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "plasma zinc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "platelet aggregation", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "platelets", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "prostate specific antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "protein electrophoresi", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "prothrombin time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "q.r.a test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "qualitative hcv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "qualitative hiv by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quality control culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantification of post transplant donor chimerism", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantification of pre transplant donor chimerism", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative culture & se", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hbv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hcv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hdv by real time pcr (qhdv)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hiv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rbc folate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "reticulocytes", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rota virus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rubella igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rubella igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.bicarbonate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.chloride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.methotrexate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.potassium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sec blood x-match/screen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum anca", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum electrolytes", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum ena profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum immunoglobulins", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum iron", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum iron/tibc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sgot (ast)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sgpt(alt)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "short synachten-17oh prog", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "short synachten-cortisol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "skin biopsy procedure chg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "skin biopsy procedure", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "skin window", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "slide consultation review", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sma 6 (gluf,bun,cr,electrolyte", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sperm antibody(auto)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sperm antibody(wife's)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spinal muscular atrophy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine ca", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine chloride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine creatinine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine phosphorous", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine potasium (non-stat entity)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine zinc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sputum for eosinophils", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool d/r concentration m", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool detail report", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool fat globules", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool occult blood", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "synovial fluid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "tegretol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "testosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thalassemia by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thalassemia pcr in blood", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thrombin time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroglobulin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroid profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroid stimulating hormo", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "torch", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total hla typing", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total iron bind.capacity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total protein group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total urine volume", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "triglyceride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "triidothyronine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "u.barbiturates", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "u.benzodiazepines", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary beta-2 microglubu", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary beta-2-microglobu", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary metabolites", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary myoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary toxicology", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine aldosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine calcium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine microalbumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine microscopy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine osmolality", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine reducing substance", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "valproic acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "vancomycin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "vdrl / rpr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "white blood cell count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "widal", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "x culture & sensi", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "none", short_name: "none", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
Patient.create(first_name: "john", middle_name: "smith", last_name: "doe", gender: "male", date_of_birth: "1968-01-01", phone: "4035552345", externalid: "123211")
Patient.create(first_name: "little", middle_name: "smith", last_name: "jonny", gender: "male", date_of_birth: "2007-11-21", phone: "2035552345", externalid: "1332221")
Patient.create(first_name: "mary", middle_name: "smith", last_name: "jane", gender: "female", date_of_birth: "1998-12-11", phone: "3035552345", externalid: "123213")
RegQuestion.create(content: 'alchohol drinking, if so, what frequency?',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'any concerned related to sexual functions, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'any other problem or concern',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'any recent occurance of shortness of breath, wheezing, heart racing, difficulty breathing while sleeping or leg swelling etc',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'during the past month have you felt depressed, down, or hopeless, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'for children < 18 years, problems or complications of pregnancy, labor, delivery, or early newborn period, adults skip this ',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'how did you hear about us',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'men\'s screening, i.e., prostrate cancer etc',minimum_age: 40,gender: 'male')
RegQuestion.create(content: 'occupation, include number of hours per week work',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'other healthcare provider, if so, include names and for what condition they are involved',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recent changes in urination, frequency, color , pain, burning sensation, difficulty starting or stopping stream of urine, blood in urine, leakage etc',minimum_age: 10,gender: 'both')
RegQuestion.create(content: 'recent changes to sense of smell, ability to chew or swallow, vision, hearing',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent changes to weight, chills, fever, excessive fatigue',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recent problems of back pain, joint pain, injuries',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of digestion, nasuea, vomiting, abdominal pain, diarrhea, constipation, blood in stool, changes in bowel movement, color or frequency etc',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of dizziness, headache, unusual numbness or tingling sensation, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'recent tests done, i.e., cholestrol, blood work, urine analysis, x-ray, please bring in test reports for accuracy',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recreational activities you enjoy',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'reproductive history, i.e., pregnancy, still births, births , mamograms, menopause, bone density test',minimum_age: 18,gender: 'female')
RegQuestion.create(content: 'smoking or pan / gutka chewing , if so then frequenct of use, if quite then what year',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'substance abuse, if so, what type of substance, quantities and frequency, if quit then what year',minimum_age: 14,gender: 'both')
Relationship.create(name: "brother")
Relationship.create(name: "father")
Relationship.create(name: "father's brother")
Relationship.create(name: "father's father")
Relationship.create(name: "father's mom")
Relationship.create(name: "father's sister")
Relationship.create(name: "mother")
Relationship.create(name: "mother's brother")
Relationship.create(name: "mother's father")
Relationship.create(name: "mother's mom")
Relationship.create(name: "mother's sister")
Relationship.create(name: "self")
Relationship.create(name: "sister")
User.create(first_name: "asim", last_name: "kaghzi", username: "akaghzi", user_type: "doctor", password: "hussain7", password_confirmation: "hussain7")
User.create(first_name: "jamila", last_name: "kureshi", username: "jkureshi", user_type: "doctor", password: "jamilah", password_confirmation: "jamilah")
Vaccine.create(name: "anthrax")
Vaccine.create(name: "cervical cancer")
Vaccine.create(name: "diphtheria")
Vaccine.create(name: "h1n1 flu (swine flu)")
Vaccine.create(name: "haemophilus influenzae type b (hib) ")
Vaccine.create(name: "hepatitis a")
Vaccine.create(name: "hepatitis b")
Vaccine.create(name: "human papillomavirus (hpv)")
Vaccine.create(name: "influenza (seasonal flu)")
Vaccine.create(name: "japanese encephalitis (je) lyme disease")
Vaccine.create(name: "measles")
Vaccine.create(name: "meningococcal")
Vaccine.create(name: "monkeypox")
Vaccine.create(name: "mumps")
Vaccine.create(name: "pertussis (whooping cough)")
Vaccine.create(name: "pneumococcal")
Vaccine.create(name: "poliomyelitis (polio)")
Vaccine.create(name: "rabies rotavirus")
Vaccine.create(name: "rubella (german measles)")
Vaccine.create(name: "shingles (herpes zoster)")
Vaccine.create(name: "smallpox")
Vaccine.create(name: "tetanus (lockjaw)")
Vaccine.create(name: "tuberculosis")
Vaccine.create(name: "typhoid fever")
Vaccine.create(name: "varicella (chickenpox)")
Vaccine.create(name: "yellow fever")
