Vaccine.create(name: "Anthrax")
Vaccine.create(name: "Cervical Cancer")
Vaccine.create(name: "Diphtheria")
Vaccine.create(name: "Hepatitis A")
Vaccine.create(name: "Hepatitis B")
Vaccine.create(name: "Haemophilus influenzae type b (Hib) ")
Vaccine.create(name: "Human Papillomavirus (HPV)")
Vaccine.create(name: "H1N1 Flu (Swine Flu)")
Vaccine.create(name: "Influenza (Seasonal Flu)")
Vaccine.create(name: "Japanese Encephalitis (JE) Lyme Disease")
Vaccine.create(name: "Measles")
Vaccine.create(name: "Meningococcal")
Vaccine.create(name: "Monkeypox")
Vaccine.create(name: "Mumps")
Vaccine.create(name: "Pertussis (Whooping Cough)")
Vaccine.create(name: "Pneumococcal")
Vaccine.create(name: "Poliomyelitis (Polio)")
Vaccine.create(name: "Rabies Rotavirus")
Vaccine.create(name: "Rubella (German Measles)")
Vaccine.create(name: "Shingles (Herpes Zoster)")
Vaccine.create(name: "Smallpox")
Vaccine.create(name: "Tetanus (Lockjaw)")
Vaccine.create(name: "Tuberculosis")
Vaccine.create(name: "Typhoid Fever")
Vaccine.create(name: "Varicella (Chickenpox)")
Vaccine.create(name: "Yellow Fever")