Disease.create(name: "Arthritis")
Disease.create(name: "Asthma")
Disease.create(name: "Blood Disorder")
Disease.create(name: "Cancer")
Disease.create(name: "Diabetes")
Disease.create(name: "Gastrointestinal")
Disease.create(name: "Genitourinary")
Disease.create(name: "Heart Problems")
Disease.create(name: "High Blood Pressure")
Disease.create(name: "High Cholesterol")
Disease.create(name: "Kidney Problems")
Disease.create(name: "Liver Problems/Hepatitis")
Disease.create(name: "Lung Problems")
Disease.create(name: "Neuro-Epilepsy")
Disease.create(name: "Neuro-Seizures")
Disease.create(name: "Other")
Disease.create(name: "Prostate")
Disease.create(name: "Psychiatric")
Disease.create(name: "Skin Disorders")
Disease.create(name: "STD")
Disease.create(name: "Thyroid")