Disease.create(name: "arthritis")
Disease.create(name: "asthma")
Disease.create(name: "blood disorder")
Disease.create(name: "cancer")
Disease.create(name: "diabetes")
Disease.create(name: "gastrointestinal")
Disease.create(name: "genitourinary")
Disease.create(name: "heart problems")
Disease.create(name: "high blood pressure")
Disease.create(name: "high cholesterol")
Disease.create(name: "kidney problems")
Disease.create(name: "liver problems/hepatitis")
Disease.create(name: "lung problems")
Disease.create(name: "neuro-epilepsy")
Disease.create(name: "neuro-seizures")
Disease.create(name: "other")
Disease.create(name: "prostate")
Disease.create(name: "psychiatric")
Disease.create(name: "skin disorders")
Disease.create(name: "std")
Disease.create(name: "thyroid")
LabTest.create(full_name: "abo blood group & rh fact", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "abo incomp titre", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "absolute eosino", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "acid fast bacilli smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "acute lukemia basic panel", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "adrenocorticotropic hormo", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "afb culture and sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "afb culture without susceptibility testing", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "afb culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "alcohol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "aldosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "alk. phos. fractionation.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "alkaline phosphatase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "amoebaiasis - iha", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ana group test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "androstenedione", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "angiotensin conver. enzy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti dsdna", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti thrombin iii", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti transglutaminase-iga", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti xa assay", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti-cardiolipin igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti-thyroglobuline ( anti-tg )", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "anti-thyroid peroxidase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "antibodies to heparin/platelet factor 4 comple", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "antistreptolysin 'o'", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "aptt inhibitor test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "aptt", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ascitic fluid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ascitic fluid-albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "b.pertussis dna by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "b12", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bence jones protein(qual)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bilirubin group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bladder cancer urovysion", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "bleeding time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood culture bottle", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood culture", short_name: "blcs", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood indices", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "blood1 x-match/screen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid ldh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "body fluid-albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "breath h2 test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "calcium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cardiac enz.profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cbc esr platelets", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ceruloplasmin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cervical smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "chlamydia trachomatis ag.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cholesterol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ckmb", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "clostridium difficile gdh antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "clostridium difficile toxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "clotting time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "complete blood count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cpk", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "creatinine clearance", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "creatinine urine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "creatinine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "crossmatch only", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "crossmatch", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "cryoprecipitate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf glucose", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf protein electrop", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "csf protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "culture & sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "culture and sensitivity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "dengue igm antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "dengue rapid ns1 antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "diff.leucocytes count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "digoxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "direct bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "direct coombs(broad spect", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "environmental allergens", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "environmental culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "enzyme histo chemistry", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "esr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "estradiol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ferritin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fibrin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fine ndl asp cyto & proc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fine needle asp cytology", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fine needle aspiratn bio", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "folic acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "follicle stimulating horm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "for gynae ogtt-gd 2hr-75gm.f,1h,2hs", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free haemoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free prostate specific ag", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free thyroxine index", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free thyroxine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "free triiodothyronine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fungus culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "fungus smear/koh prep", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "g6pd quantitative", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glucose challenge test.1 fl tube", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glucose fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glucose random", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "glycated hemoglobin (a1c)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gram stain", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gtt 3hr-75gm.8--12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gtt-4hr 09 fl tubes required.8-12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "gtt-5 hrs 11 fl tubes required.8-12 hrs fasting", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "h-urine bile pigment", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "h-urine bile salts", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "h.pylori antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "haemoglobin haematocrit", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "haptoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hb electroph. on acid ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hb electrophoresis report", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hb h inclusion", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hbv genotyping", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hcv rna genotyping", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hemosiderin urine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep b.surface antigen quantitative", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.a antibody igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b core igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b core total", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b sur. antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.b.sur.antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.be antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.be antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hep.delta antibody", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis a virus ab tot.", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis b virus by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis e virus (hev) by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis e virus (igg)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis e virus igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatitis profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatits b profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hepatits c virus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "high density lipoprotein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "high sensitive crp", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "hiv by western blot", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "infectious mono", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "influenza a h1n1 pcr minus swab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "influenza a h1n1 pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "insulin sensitivity test with ogtt", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "insulin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "ldh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "legionella urine antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "lipase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "lipid profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "lipoprot.electrophoresis", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "liver kidney microsoml ab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "liver profile (lft)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "low density lipoprotein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "magnesium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "malaria parasites", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "mantoux test (ppd)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "mycoplasma pneumoniae ab", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "neonatal bilirubin group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "neonatal total bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "neonatal tsh", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "nt-pro bnp ii", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "pap smear procedure chg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "pap smear", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "parathormone *", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "paroxysmal nocturnal haem", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "phenobarbital", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "phenytoin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "phosphorus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "plasma zinc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "platelet aggregation", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "platelets", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "prostate specific antigen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "protein electrophoresi", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "prothrombin time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "q.r.a test", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "qualitative hcv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "qualitative hiv by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quality control culture", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantification of post transplant donor chimerism", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantification of pre transplant donor chimerism", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative culture & se", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hbv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hcv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hdv by real time pcr (qhdv)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "quantitative hiv pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rbc folate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "reticulocytes", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rota virus", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rubella igg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "rubella igm", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.bicarbonate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.chloride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.methotrexate", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.potassium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "s.sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sec blood x-match/screen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum albumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum anca", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum electrolytes", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum ena profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum immunoglobulins", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum iron", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum iron/tibc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "serum protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sgot (ast)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sgpt(alt)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "short synachten-17oh prog", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "short synachten-cortisol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "skin biopsy procedure chg", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "skin biopsy procedure", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "skin window", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "slide consultation review", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sma 6 (gluf,bun,cr,electrolyte", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sperm antibody(auto)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sperm antibody(wife's)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spinal muscular atrophy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine ca", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine chloride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine creatinine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine phosphorous", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine potasium (non-stat entity)", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "spot urine zinc", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "sputum for eosinophils", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool d/r concentration m", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool detail report", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool fat globules", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "stool occult blood", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "synovial fluid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "tegretol", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "testosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thalassemia by pcr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thalassemia pcr in blood", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thrombin time", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroglobulin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroid profile", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroid stimulating hormo", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "thyroxin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "torch", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total bilirubin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total hla typing", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total iron bind.capacity", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total protein group", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "total urine volume", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "triglyceride", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "triidothyronine", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "u.barbiturates", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "u.benzodiazepines", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary beta-2 microglubu", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary beta-2-microglobu", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary copper", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary metabolites", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary myoglobin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urinary toxicology", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine aldosterone", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine amylase", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine calcium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine microalbumin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine microscopy", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine osmolality", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine ph", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine protein", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine reducing substance", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine sodium", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine urea nitrogen", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "urine uric acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "valproic acid", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "vancomycin", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "vdrl / rpr", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "white blood cell count", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "widal", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "x culture & sensi", short_name: "", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
LabTest.create(full_name: "none", short_name: "none", unit_of_measure: "text", low_threshold: 0.0, high_threshold: 0.0)
Patient.create(first_name: "john", middle_name: "smith", last_name: "doe", gender: "male", date_of_birth: "1968-01-01", phone: "4035552345", externalid: "123211")
Patient.create(first_name: "little", middle_name: "smith", last_name: "jonny", gender: "male", date_of_birth: "2007-11-21", phone: "2035552345", externalid: "1332221")
Patient.create(first_name: "mary", middle_name: "smith", last_name: "jane", gender: "female", date_of_birth: "1998-12-11", phone: "3035552345", externalid: "123213")
RegQuestion.create(content: 'alchohol drinking, if so, what frequency?',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'any concerned related to sexual functions, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'any other problem or concern',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'any recent occurance of shortness of breath, wheezing, heart racing, difficulty breathing while sleeping or leg swelling etc',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'during the past month have you felt depressed, down, or hopeless, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'for children < 18 years, problems or complications of pregnancy, labor, delivery, or early newborn period, adults skip this ',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'how did you hear about us',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'men\'s screening, i.e., prostrate cancer etc',minimum_age: 40,gender: 'male')
RegQuestion.create(content: 'occupation, include number of hours per week work',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'other healthcare provider, if so, include names and for what condition they are involved',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recent changes in urination, frequency, color , pain, burning sensation, difficulty starting or stopping stream of urine, blood in urine, leakage etc',minimum_age: 10,gender: 'both')
RegQuestion.create(content: 'recent changes to sense of smell, ability to chew or swallow, vision, hearing',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent changes to weight, chills, fever, excessive fatigue',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recent problems of back pain, joint pain, injuries',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of digestion, nasuea, vomiting, abdominal pain, diarrhea, constipation, blood in stool, changes in bowel movement, color or frequency etc',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'recent problems of dizziness, headache, unusual numbness or tingling sensation, if none, put none',minimum_age: 18,gender: 'both')
RegQuestion.create(content: 'recent tests done, i.e., cholestrol, blood work, urine analysis, x-ray, please bring in test reports for accuracy',minimum_age: 0,gender: 'both')
RegQuestion.create(content: 'recreational activities you enjoy',minimum_age: 5,gender: 'both')
RegQuestion.create(content: 'reproductive history, i.e., pregnancy, still births, births , mamograms, menopause, bone density test',minimum_age: 18,gender: 'female')
RegQuestion.create(content: 'smoking or pan / gutka chewing , if so then frequenct of use, if quite then what year',minimum_age: 14,gender: 'both')
RegQuestion.create(content: 'substance abuse, if so, what type of substance, quantities and frequency, if quit then what year',minimum_age: 14,gender: 'both')
Relationship.create(name: "brother")
Relationship.create(name: "father")
Relationship.create(name: "father's brother")
Relationship.create(name: "father's father")
Relationship.create(name: "father's mom")
Relationship.create(name: "father's sister")
Relationship.create(name: "mother")
Relationship.create(name: "mother's brother")
Relationship.create(name: "mother's father")
Relationship.create(name: "mother's mom")
Relationship.create(name: "mother's sister")
Relationship.create(name: "self")
Relationship.create(name: "sister")
User.create(first_name: "asim", last_name: "kaghzi", username: "akaghzi", user_type: "doctor", password: "hussain7", password_confirmation: "hussain7")
User.create(first_name: "jamila", last_name: "kureshi", username: "jkureshi", user_type: "doctor", password: "jamilah", password_confirmation: "jamilah")
Vaccine.create(name: "anthrax")
Vaccine.create(name: "cervical cancer")
Vaccine.create(name: "diphtheria")
Vaccine.create(name: "h1n1 flu (swine flu)")
Vaccine.create(name: "haemophilus influenzae type b (hib) ")
Vaccine.create(name: "hepatitis a")
Vaccine.create(name: "hepatitis b")
Vaccine.create(name: "human papillomavirus (hpv)")
Vaccine.create(name: "influenza (seasonal flu)")
Vaccine.create(name: "japanese encephalitis (je) lyme disease")
Vaccine.create(name: "measles")
Vaccine.create(name: "meningococcal")
Vaccine.create(name: "monkeypox")
Vaccine.create(name: "mumps")
Vaccine.create(name: "pertussis (whooping cough)")
Vaccine.create(name: "pneumococcal")
Vaccine.create(name: "poliomyelitis (polio)")
Vaccine.create(name: "rabies rotavirus")
Vaccine.create(name: "rubella (german measles)")
Vaccine.create(name: "shingles (herpes zoster)")
Vaccine.create(name: "smallpox")
Vaccine.create(name: "tetanus (lockjaw)")
Vaccine.create(name: "tuberculosis")
Vaccine.create(name: "typhoid fever")
Vaccine.create(name: "varicella (chickenpox)")
Vaccine.create(name: "yellow fever")
MedicationRoute.create(full_name: "AURICULAR (OTIC)", description: "Administration to or by way of the ear.", short_name: "OTIC")
MedicationRoute.create(full_name: "BUCCAL", description: "Administration directed toward the cheek, generally from within the mouth.", short_name: "BUCCAL")
MedicationRoute.create(full_name: "CONJUNCTIVAL", description: "Administration to the conjunctiva, the delicate membrane that lines the eyelids and covers the exposed surface of the eyeball.", short_name: "CONJUNC")
MedicationRoute.create(full_name: "CUTANEOUS", description: "Administration to the skin.", short_name: "CUTAN")
MedicationRoute.create(full_name: "DENTAL", description: "Administration to a tooth or teeth.", short_name: "DENTAL")
MedicationRoute.create(full_name: "ELECTRO-OSMOSIS", description: "Administration of through the diffusion of substance through a membrane in an electric field.", short_name: "EL-OSMOS")
MedicationRoute.create(full_name: "ENDOCERVICAL", description: "Administration within the canal of the cervix uteri.  Synonymous with the term intracervical..", short_name: "E-CERVIC")
MedicationRoute.create(full_name: "ENDOSINUSIAL", description: "Administration within the nasal sinuses of the head.", short_name: "E-SINUS")
MedicationRoute.create(full_name: "ENDOTRACHEAL", description: "Administration directly into the trachea.", short_name: "E-TRACHE")
MedicationRoute.create(full_name: "ENTERAL", description: "Administration directly into the intestines.", short_name: "ENTER")
MedicationRoute.create(full_name: "EPIDURAL", description: "Administration upon or over the dura mater.", short_name: "EPIDUR")
MedicationRoute.create(full_name: "EXTRA‑AMNIOTIC", description: "Administration to the outside of the membrane enveloping the fetus", short_name: "X-AMNI")
MedicationRoute.create(full_name: "EXTRACORPOREAL", description: "Administration outside of the body.", short_name: "X-CORPOR")
MedicationRoute.create(full_name: "HEMODIALYSIS", description: "Administration through hemodialysate fluid.", short_name: "HEMO")
MedicationRoute.create(full_name: "INFILTRATION", description: "Administration that results in substances passing into tissue spaces or into cells.", short_name: "INFIL")
MedicationRoute.create(full_name: "INTERSTITIAL", description: "Administration to or in the interstices of a tissue.", short_name: "INTERSTIT")
MedicationRoute.create(full_name: "INTRA-ABDOMINAL", description: "Administration within the abdomen.", short_name: "I-ABDOM")
MedicationRoute.create(full_name: "INTRA-AMNIOTIC", description: "Administration within the amnion.", short_name: "I-AMNI")
MedicationRoute.create(full_name: "INTRA-ARTERIAL", description: "Administration within an artery or arteries.", short_name: "I-ARTER")
MedicationRoute.create(full_name: "INTRA-ARTICULAR", description: "Administration within a joint.", short_name: "I-ARTIC")
MedicationRoute.create(full_name: "INTRABILIARY", description: "Administration within the bile, bile ducts or gallbladder.", short_name: "I-BILI")
MedicationRoute.create(full_name: "INTRABRONCHIAL", description: "Administration within a bronchus.", short_name: "I-BRONCHI")
MedicationRoute.create(full_name: "INTRABURSAL", description: "Administration within a bursa.", short_name: "I-BURSAL")
MedicationRoute.create(full_name: "INTRACARDIAC", description: "Administration with the heart.", short_name: "I-CARDI")
MedicationRoute.create(full_name: "INTRACARTILAGINOUS", description: "Administration within a cartilage; endochondral.", short_name: "I-CARTIL")
MedicationRoute.create(full_name: "INTRACAUDAL", description: "Administration within the cauda equina.", short_name: "I-CAUDAL")
MedicationRoute.create(full_name: "INTRACAVERNOUS", description: "Administration within a pathologic cavity, such as  occurs in the lung in tuberculosis.", short_name: "I-CAVERN")
MedicationRoute.create(full_name: "INTRACAVITARY", description: "Administration within a non-pathologic cavity, such as that of the cervix, uterus, or penis, or such as that which is formed as the result of a wound.", short_name: "I-CAVIT")
MedicationRoute.create(full_name: "INTRACEREBRAL", description: "Administration within the cerebrum.", short_name: "I-CERE")
MedicationRoute.create(full_name: "INTRACISTERNAL", description: "Administration within the cisterna magna cerebellomedularis.", short_name: "I-CISTERN")
MedicationRoute.create(full_name: "INTRACORNEAL", description: "Administration within the cornea (the transparent structure forming the anterior part of the fibrous tunic of the eye).", short_name: "I-CORNE")
MedicationRoute.create(full_name: "INTRACORONAL, DENTAL", description: "Administration of a drug within a portion of a tooth which is covered by enamel and which is separated from the roots by a slightly constricted region known as the neck.", short_name: "I-CORONAL")
MedicationRoute.create(full_name: "INTRACORONARY", description: "Administration within the coronary arteries.", short_name: "I-CORONARY")
MedicationRoute.create(full_name: "INTRACORPORUS CAVERNOSUM", description: "Administration within the dilatable spaces of the corporus cavernosa of the penis.", short_name: "I-CORPOR")
MedicationRoute.create(full_name: "INTRADERMAL", description: "Administration within the dermis.", short_name: "I-DERMAL")
MedicationRoute.create(full_name: "INTRADISCAL", description: "Administration within a disc.", short_name: "I-DISCAL")
MedicationRoute.create(full_name: "INTRADUCTAL", description: "Administration within the duct of a gland.", short_name: "I-DUCTAL")
MedicationRoute.create(full_name: "INTRADUODENAL", description: "Administration within the duodenum.", short_name: "I-DUOD")
MedicationRoute.create(full_name: "INTRADURAL", description: "Administration within or beneath the dura.", short_name: "I-DURAL")
MedicationRoute.create(full_name: "INTRAEPIDERMAL", description: "Administration within the epidermis.", short_name: "I-EPIDERM")
MedicationRoute.create(full_name: "INTRAESOPHAGEAL", description: "Administration within the esophagus.", short_name: "I-ESO")
MedicationRoute.create(full_name: "INTRAGASTRIC", description: "Administration within the stomach.", short_name: "I-GASTRIC")
MedicationRoute.create(full_name: "INTRAGINGIVAL", description: "Administration within the gingivae.", short_name: "I-GINGIV")
MedicationRoute.create(full_name: "INTRAILEAL", description: "Administration within the distal portion of the small intestine, from the jejunum to the cecum.", short_name: "I-ILE")
MedicationRoute.create(full_name: "INTRALESIONAL", description: "Administration within or introduced directly into a localized lesion.", short_name: "I-LESION")
MedicationRoute.create(full_name: "INTRALUMINAL", description: "Administration within the lumen of a tube.", short_name: "I-LUMIN")
MedicationRoute.create(full_name: "INTRALYMPHATIC", description: "Administration within the lymph.", short_name: "I-LYMPHAT")
MedicationRoute.create(full_name: "INTRAMEDULLARY", description: "Administration within the marrow cavity of a bone.", short_name: "I-MEDUL")
MedicationRoute.create(full_name: "INTRAMENINGEAL", description: "Administration within the meninges (the three membranes that envelope the brain and spinal cord).", short_name: "I-MENIN")
MedicationRoute.create(full_name: "INTRAMUSCULAR", description: "Administration within a muscle.", short_name: "IM")
MedicationRoute.create(full_name: "INTRAOCULAR", description: "Administration within the eye.", short_name: "I-OCUL")
MedicationRoute.create(full_name: "INTRAOVARIAN", description: "Administration within the ovary.", short_name: "I-OVAR")
MedicationRoute.create(full_name: "INTRAPERICARDIAL", description: "Administration within the pericardium.", short_name: "I-PERICARD")
MedicationRoute.create(full_name: "INTRAPERITONEAL", description: "Administration within the peritoneal cavity.", short_name: "I-PERITON")
MedicationRoute.create(full_name: "INTRAPLEURAL", description: "Administration within the pleura.", short_name: "I-PLEURAL")
MedicationRoute.create(full_name: "INTRAPROSTATIC", description: "Administration within the prostate gland.", short_name: "I-PROSTAT")
MedicationRoute.create(full_name: "INTRAPULMONARY", description: "Administration within the lungs or its bronchi.", short_name: "I-PULMON")
MedicationRoute.create(full_name: "INTRASINAL", description: "Administration within the nasal or periorbital sinuses.", short_name: "I-SINAL")
MedicationRoute.create(full_name: "INTRASPINAL", description: "Administration within the vertebral column.", short_name: "I-SPINAL")
MedicationRoute.create(full_name: "INTRASYNOVIAL", description: "Administration within the synovial cavity of a joint.", short_name: "I-SYNOV")
MedicationRoute.create(full_name: "INTRATENDINOUS", description: "Administration within a tendon.", short_name: "I-TENDIN")
MedicationRoute.create(full_name: "INTRATESTICULAR", description: "Administration within the testicle.", short_name: "I-TESTIC")
MedicationRoute.create(full_name: "INTRATHECAL", description: "Administration within the cerebrospinal fluid at any level of the cerebrospinal axis, including injection into the cerebral ventricles.", short_name: "IT")
MedicationRoute.create(full_name: "INTRATHORACIC", description: "Administration within the thorax (internal to the ribs); synonymous with the term endothoracic.", short_name: "I-THORAC")
MedicationRoute.create(full_name: "INTRATUBULAR", description: "Administration within the tubules of an organ.", short_name: "I-TUBUL")
MedicationRoute.create(full_name: "INTRATUMOR", description: "Administration within a tumor.", short_name: "I-TUMOR")
MedicationRoute.create(full_name: "INTRATYMPANIC", description: "Administration within the aurus media.", short_name: "I-TYMPAN")
MedicationRoute.create(full_name: "INTRAUTERINE", description: "Administration within the uterus.", short_name: "I-UTER")
MedicationRoute.create(full_name: "INTRAVASCULAR", description: "Administration within a vessel or vessels.", short_name: "I-VASC")
MedicationRoute.create(full_name: "INTRAVENOUS", description: "Administration within or into a vein or veins.", short_name: "IV")
MedicationRoute.create(full_name: "INTRAVENOUS BOLUS", description: "Administration within or into a vein or veins all at once.", short_name: "IV BOLUS")
MedicationRoute.create(full_name: "INTRAVENOUS DRIP", description: "Administration within or into a vein or veins over a sustained period of time.", short_name: "IV DRIP")
MedicationRoute.create(full_name: "INTRAVENTRICULAR", description: "Administration within a ventricle.", short_name: "I-VENTRIC")
MedicationRoute.create(full_name: "INTRAVESICAL", description: "Administration within the bladder.", short_name: "I-VESIC")
MedicationRoute.create(full_name: "INTRAVITREAL", description: "Administration within the vitreous body of the eye.", short_name: "I-VITRE")
MedicationRoute.create(full_name: "IONTOPHORESIS", description: "Administration by means of an electric current where ions of soluble salts migrate into the tissues of the body.", short_name: "ION")
MedicationRoute.create(full_name: "IRRIGATION", description: "Administration to bathe or flush open wounds or body cavities.", short_name: "IRRIG")
MedicationRoute.create(full_name: "LARYNGEAL", description: "Administration directly upon the larynx.", short_name: "LARYN")
MedicationRoute.create(full_name: "NASAL", description: "Administration to the nose; administered by way of the nose.", short_name: "NASAL")
MedicationRoute.create(full_name: "NASOGASTRIC", description: "Administration through the nose and into the stomach, usually by means of a tube.", short_name: "NG")
MedicationRoute.create(full_name: "OCCLUSIVE DRESSING TECHNIQUE", description: "Administration by the topical route which is then covered by a dressing which occludes the area.", short_name: "OCCLUS")
MedicationRoute.create(full_name: "OPHTHALMIC", description: "Administration  to the external eye.", short_name: "OPHTHALM")
MedicationRoute.create(full_name: "ORAL", description: "Administration to or by way of the mouth.", short_name: "ORAL")
MedicationRoute.create(full_name: "OROPHARYNGEAL", description: "Administration directly to the mouth and pharynx.", short_name: "ORO")
MedicationRoute.create(full_name: "PARENTERAL", description: "Administration by injection, infusion, or implantation.", short_name: "PAREN")
MedicationRoute.create(full_name: "PERCUTANEOUS", description: "Administration through the skin.", short_name: "PERCUT")
MedicationRoute.create(full_name: "PERIARTICULAR", description: "Administration around a joint.", short_name: "P-ARTIC")
MedicationRoute.create(full_name: "PERIDURAL", description: "Administration to the outside of the dura mater of the spinal cord..", short_name: "P-DURAL")
MedicationRoute.create(full_name: "PERINEURAL", description: "Administration surrounding a nerve or nerves.", short_name: "P-NEURAL")
MedicationRoute.create(full_name: "PERIODONTAL", description: "Administration around a tooth.", short_name: "P-ODONT")
MedicationRoute.create(full_name: "RECTAL", description: "Administration to the rectum.", short_name: "RECTAL")
MedicationRoute.create(full_name: "RESPIRATORY (INHALATION)", description: "Administration within the respiratory tract by inhaling orally or nasally for local or systemic effect.", short_name: "RESPIR")
MedicationRoute.create(full_name: "RETROBULBAR", description: "Administration behind the pons or behind the eyeball.", short_name: "RETRO")
MedicationRoute.create(full_name: "SOFT TISSUE", description: "Administration into any soft tissue.", short_name: "SOFT TIS")
MedicationRoute.create(full_name: "SUBARACHNOID", description: "Administration beneath the arachnoid.", short_name: "S-ARACH")
MedicationRoute.create(full_name: "SUBCONJUNCTIVAL", description: "Administration beneath the conjunctiva.", short_name: "S-CONJUNC")
MedicationRoute.create(full_name: "SUBCUTANEOUS", description: "Administration beneath the skin; hypodermic.  Synonymous with the term SUBDERMAL.", short_name: "SC")
MedicationRoute.create(full_name: "SUBLINGUAL", description: "Administration beneath the tongue.", short_name: "SL")
MedicationRoute.create(full_name: "SUBMUCOSAL", description: "Administration beneath the mucous membrane.", short_name: "S-MUCOS")
MedicationRoute.create(full_name: "TOPICAL", description: "Administration to a particular spot on the outer surface of the body.  The E2B term TRANSMAMMARY is a subset of the term TOPICAL.", short_name: "TOPIC")
MedicationRoute.create(full_name: "TRANSDERMAL", description: "Administration through the dermal layer of the skin to the systemic circulation by diffusion.", short_name: "T-DERMAL")
MedicationRoute.create(full_name: "TRANSMUCOSAL", description: "Administration across the mucosa.", short_name: "T-MUCOS")
MedicationRoute.create(full_name: "TRANSPLACENTAL", description: "Administration through or across the placenta.", short_name: "T-PLACENT")
MedicationRoute.create(full_name: "TRANSTRACHEAL", description: "Administration through the wall of the trachea.", short_name: "T-TRACHE")
MedicationRoute.create(full_name: "TRANSTYMPANIC", description: "Administration across or through the tympanic cavity.", short_name: "T-TYMPAN")
MedicationRoute.create(full_name: "URETERAL", description: "Administration into the ureter.", short_name: "URETER")
MedicationRoute.create(full_name: "URETHRAL", description: "Administration into the urethra.", short_name: "URETH")
MedicationRoute.create(full_name: "VAGINAL", description: "Administration into the vagina.", short_name: "VAGIN")
