# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
RegQuestion.create(content: 'email',minimum_age: 10,sex: 'both')
RegQuestion.create(content: 'alternate phone',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'address [include city, province, postal code ]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'emergency contact [include name, relationship, phone number]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'insurance carrier',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'insurance member id [include employer, the person you are covered under]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'insurance guarantor [the name of person who is primary insured]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'how did you hear about us',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'current medical problems [put none, if none]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'past medical problems [excluding surgeries]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'list surguries [include surgeon name, hospital, date of surgery etc]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'for children < 18 years, problems or complications of pregnancy, labor, delivery, or early newborn period, adults skip this ',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'allurgies to food or medication or any other substances',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'list of all medication taking currently, dosage, and frequency [include any food supplements and vitamins, and over the counter medicines]',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'other healthcare provider, if so, include names and for what condition they are involved',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'indicate history of medical problems of your family and your relationship, like heart disease, cancer, brother , mother etc',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'vaccination record, for children please bring in vaccination certificates, for adults list year and type of vaccination',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'recent tests done, i.e., cholestrol, blood work, urine analysis, x-ray, please bring in test reports for accuracy',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'reproductive history, i.e., pregnancy, still births, births , mamograms, menopause, bone density test',minimum_age: 14,sex: 'female')
RegQuestion.create(content: 'men\'s screening, i.e., prostrate cancer etc',minimum_age: 18,sex: 'male')
RegQuestion.create(content: 'occupation, include number of hours per week work',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'recreational activities you enjoy',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'smoking or pan / gutka chewing , if so then frequenct of use, if quite then what year',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'alchohol drinking, if so, what frequency?',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'substance abuse, if so, what type of substance, quantities and frequency, if quit then what year',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'recent changes to weight, chills, fever, excessive fatigue',minimum_age: 0,sex: 'both')
RegQuestion.create(content: 'recent changes to sense of smell, ability to chew or swallow, vision, hearing',minimum_age: 5,sex: 'both')
RegQuestion.create(content: 'any recent occurance of shortness of breath, wheezing, heart racing, difficulty breathing while sleeping or leg swelling etc',minimum_age: 5,sex: 'both')
RegQuestion.create(content: 'recent problems of digestion, nasuea, vomiting, abdominal pain, diarrhea, constipation, blood in stool, changes in bowel movement, color or frequency etc',minimum_age: 5,sex: 'both')
RegQuestion.create(content: 'recent problems of back pain, joint pain, injuries',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'recent problems of dizziness, headache, unusual numbness or tingling sensation, if none, put none',minimum_age: 5,sex: 'both')
RegQuestion.create(content: 'during the past month have you felt depressed, down, or hopeless, if none, put none',minimum_age: 10,sex: 'both')
RegQuestion.create(content: 'any concerned related to sexual functions, if none, put none',minimum_age: 18,sex: 'both')
RegQuestion.create(content: 'recent changes in urination, frequency, color , pain, burning sensation, difficulty starting or stopping stream of urine, blood in urine, leakage etc',minimum_age: 10,sex: 'both')
RegQuestion.create(content: 'any other problem or concern',minimum_age: 0,sex: 'both')